using System.Collections;
using System.Collections.Generic;
using System.Linq;
using DG.Tweening;
using UnityEngine;

/// <summary>
/// Bombs are generated by bomber planes colliding with BombTriggers - fall at random rates and explode on impact. 
/// </summary>
public class Bomb : MonoBehaviour {
    //world manager ref
    WorldManager worldMan;
    EffectsManager effectsMan;
    CameraSwitcher camSwitcher;

    //physics vars
    SphereCollider bombCol;
    Rigidbody bombBody;
    PooledObject _pooledObj;
    public float moveSpeedOverTime;
    public float startSpeed = 10000f;
    public bool randomizeSpeed;
    public Vector2 randomStartSpeedRange = new Vector2(10000f, 15000f);
    public Vector2 randomMoveSpeedRange = new Vector2(2500f, 5000f);
    [Tooltip("Include tags like Building, Ground, Car, Human, Player")]
    public string[] bombTags;
    
    //audio vars
    AudioSource bombAudio;
    public AudioClip[] bombfalls;

    //explosion prefab
    public GameObject explosionPrefab;
    public Transform explosionParent;

    [SerializeField] private bool transitionBomb;
    private CamObject camObj;
    public CamObject CamObj 
    {
        get
        {
            if (camObj == null)
            {
                camObj = GetComponent<CamObject>();
            }

            return camObj;
        }
    }
    

    //only for kill player bomb
    [HideInInspector] public MoveTowards moveTowards;
    [HideInInspector] public Transform playerDest;

    void Awake()
    {
        //world man and add to list
        worldMan = FindObjectOfType<WorldManager>();
        effectsMan = FindObjectOfType<EffectsManager>();
        camSwitcher = worldMan.GetComponent<CameraSwitcher>();

        //get comp refs
        bombCol = GetComponent<SphereCollider>();
        bombBody = GetComponent<Rigidbody>();
        bombAudio = GetComponent<AudioSource>();

        //set parent for explosion
        explosionParent = GameObject.FindGameObjectWithTag("ExpParent").transform;
    }

    void Start () 
    {
        //pooled 
        _pooledObj = GetComponent<PooledObject>();
    }

    //called by bomber
    public void SetBombFall()
    {
        //set fall sound
        int randomFall = Random.Range(0, bombfalls.Length);
        bombAudio.clip = bombfalls[randomFall];
        bombAudio.Play();
        
        //physx
        bombBody.isKinematic = false;
        bombBody.AddForce(0f, startSpeed, 0f);

        //Randomize speed?
        if (randomizeSpeed)
        {
            startSpeed = Random.Range(randomStartSpeedRange.x, randomStartSpeedRange.y);
            moveSpeedOverTime = Random.Range(randomMoveSpeedRange.x, randomMoveSpeedRange.y);
        }
    }
    
	void FixedUpdate ()
    {
        //fall force 
        bombBody.AddForce(0, -moveSpeedOverTime, 0);
        
        //y check - once below 0 just explode. 
        if(transform.position.y < -150f)
        {
            ResetBomb();
        }
    }
    
    void OnTriggerEnter(Collider other)
    {
        //collision checks 
        if (bombTags.Contains(other.gameObject.tag)) 
        {
            print(other.gameObject.tag);
            SpawnExplosion(other.gameObject);
        }
        //Going after parents/player - await desired tag.
        else if(playerDest && moveTowards)
        {
            Debug.Log("Special bomb awaits its Human Target!");
        }
        //Normal bomb hit something it shouldn't - reset. 
        else
        {
            ResetBomb();
        }
    }
    
    void SpawnExplosion(GameObject obj)
    {
        //Debug.Log("bomb went off");
        Vector3 spawnPos = transform.position;
        GameObject explosion = effectsMan.explosionPooler.GrabObject();
        //set pos & angle & parent
        explosion.transform.position = spawnPos;
        explosion.transform.localEulerAngles = new Vector3(-90, 0, 0);
        explosion.transform.SetParent(explosionParent); 
        
        if(obj != null)
        {
            //parent to building so when it falls, explosion falls with it
            if (obj.CompareTag("Building"))
            {
                explosion.transform.SetParent(obj.transform);
            }
        }
        
        //killing player/parents
        if (playerDest && moveTowards)
        {
            //pass the explosion along and FreezeTime
            Explosion exploded = explosion.GetComponent<Explosion>();
            camSwitcher.FreezeTime(exploded);
            
            //destroy this bomb once and for all 
            Destroy(gameObject);
        }
        //a transition bomb with a camera 
        else if (transitionBomb)
        {
            //remove this bomb camera from the cam switcher list
            camSwitcher.RemoveCamObject(CamObj);
            
            //transition to nearest cam obj
            camSwitcher.GetClosestCamObject(transform.position);
            
            //destroy this bomb once and for all 
            Destroy(gameObject);
        }
        //normal bomb reset 
        else
        {
            ResetBomb();
        }
    }

    void ResetBomb()
    {
        //check for moveTowards
        if (moveTowards)
        {
            moveTowards.enabled = false;
        }
        //stop audio 
        bombAudio.Stop();
        //zero velocity
        bombBody.velocity = Vector3.zero;
        //disable forces 
        bombBody.isKinematic = true;
        //return to pool
        _pooledObj.ReturnToPool();
    }
}
